version: "3.8"

services:
  mercado-db:
    image: postgres:15-alpine
    container_name: mercado_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2007
      - POSTGRES_DB=mercado_db
    ports:
      - "5435:5432"
    volumes:
      - mercado_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mercado_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mercado_network

  mercado-backend:
    build:
      context: .\back-end
      dockerfile: Dockerfile
    container_name: mercado_backend
    restart: always
    ports:
      - "9090:8081"
    environment:
      - DB_URL=jdbc:postgresql://mercado-db:5432/mercado_db
      - DB_USER=postgres
      - DB_PASSWORD=2007
    depends_on:
      mercado-db:
        condition: service_healthy
    networks:
      - mercado_network

  mercado-front:
    build:
      context: .\front-end
      dockerfile: Dockerfile
    container_name: mercado_frontend
    restart: always
    ports:
      - "9091:4200"
    depends_on:
      - mercado-backend
    networks:
      - mercado_network

volumes:
  mercado_data:

networks:
  mercado_network:
    driver: bridge
