version: '3.8'

services:
  mercado-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
    container_name: mercado_frontend
    restart: always
    ports:
      - "3005:4200" 
    networks:
      - web_network

networks:
  web_network:
    external: true